# Generated by Django 5.2.14 on 2026-06-06 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('alert_threshold', models.PositiveSmallIntegerField(default=85)),
            ],
            options={
                'ordering': ('category__name',),
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('savings', 'Savings'), ('investment', 'Investment'), ('credit', 'Credit')], max_length=24)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('institution', models.CharField(blank=True, max_length=128)),
                ('color_token', models.CharField(default='emerald', max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(choices=[('cleared', 'Cleared'), ('pending', 'Pending'), ('scheduled', 'Scheduled')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ('-transaction_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=24)),
                ('icon', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('cash_flow_chart_default', models.CharField(choices=[('bars', 'Bars'), ('line', 'Line'), ('tradingview', 'TradingView'), ('candles', 'Candles'), ('structure', 'Structure')], default='bars', max_length=16)),
                ('default_currency', models.CharField(default='USD', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
