# Generated by Django 5.2.14 on 2026-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('category__name',), 'verbose_name': 'Бюджет', 'verbose_name_plural': 'Бюджеты'},
        ),
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'ordering': ('name',), 'verbose_name': 'Финансовый счет', 'verbose_name_plural': 'Финансовые счета'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-transaction_date', '-created_at'), 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ('kind', 'name'), 'verbose_name': 'Категория транзакций', 'verbose_name_plural': 'Категории транзакций'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='kind',
            field=models.CharField(choices=[('cash', 'Наличные'), ('savings', 'Сбережения'), ('investment', 'Инвестиции'), ('credit', 'Кредит')], max_length=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('cleared', 'Проведена'), ('pending', 'В ожидании'), ('scheduled', 'Запланирована')], max_length=24),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='kind',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('transfer', 'Перевод')], max_length=24),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cash_flow_chart_default',
            field=models.CharField(choices=[('bars', 'Столбцы'), ('line', 'Кривая'), ('tradingview', 'Область'), ('candles', 'Свечи'), ('structure', 'Структура')], default='bars', max_length=16),
        ),
    ]
