# Generated by Django 5.2.14 on 2026-06-06 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountdepositprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_profile', to='app.account'),
        ),
        migrations.AddField(
            model_name='accounttaxprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='app.account'),
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='app.category'),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cryptoassetnetwork',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_links', to='app.cryptoasset'),
        ),
        migrations.AddField(
            model_name='cryptoholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='app.cryptoasset'),
        ),
        migrations.AddField(
            model_name='cryptoholding',
            name='asset_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='app.cryptoassetnetwork'),
        ),
        migrations.AddField(
            model_name='cryptonetwork',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_networks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cryptoassetnetwork',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='app.cryptonetwork'),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='app.cryptonetwork'),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cryptoholding',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='app.cryptowallet'),
        ),
        migrations.AddField(
            model_name='cryptoholding',
            name='price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_priced_holdings', to='app.currency'),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='app.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_exchange_rates', to='app.currency', verbose_name='Базовая валюта'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='quote_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_exchange_rates', to='app.currency', verbose_name='Котируемая валюта'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_notifications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationreceipt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='app.notification'),
        ),
        migrations.AddField(
            model_name='notificationreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_notification_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='app.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='app.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('owner', 'kind', 'slug'), name='finance_category_owner_kind_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='finance_category_owner_scope_check'),
        ),
        migrations.AddConstraint(
            model_name='cryptoasset',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='finance_crypto_asset_owner_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='cryptoasset',
            constraint=models.UniqueConstraint(fields=('owner', 'symbol'), name='finance_crypto_asset_owner_symbol_unique'),
        ),
        migrations.AddConstraint(
            model_name='cryptoasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='finance_crypto_asset_owner_scope_check'),
        ),
        migrations.AddConstraint(
            model_name='cryptonetwork',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='finance_crypto_network_owner_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='cryptonetwork',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='finance_crypto_network_owner_scope_check'),
        ),
        migrations.AddConstraint(
            model_name='cryptoassetnetwork',
            constraint=models.UniqueConstraint(fields=('asset', 'network', 'contract_address'), name='finance_crypto_asset_network_unique'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['owner', 'network'], name='app_cryptow_owner_i_005ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['owner', 'is_active'], name='app_cryptow_owner_i_46033c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cryptowallet',
            constraint=models.UniqueConstraint(fields=('owner', 'network', 'name'), name='finance_crypto_wallet_owner_network_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='cryptoholding',
            constraint=models.UniqueConstraint(fields=('wallet', 'asset', 'asset_network', 'wallet_address'), name='finance_crypto_holding_wallet_asset_network_address_unique'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['owner', 'is_active'], name='app_budget_owner_i_572939_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['owner', 'start_date', 'end_date'], name='app_budget_owner_i_c36d77_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('owner', 'category', 'period', 'start_date'), name='finance_budget_owner_category_period_start_unique'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='finance_budget_date_range_check'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'status'], name='app_account_owner_i_fbacb1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'kind'], name='app_account_owner_i_77a749_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'currency'), name='finance_account_owner_name_currency_unique'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='finance_exchange_rate_distinct_pair_check'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'rate_date', 'source'), name='finance_exchange_rate_pair_date_source_unique'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scope', 'is_active', 'published_at'], name='app_notific_scope_e4974c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_active', 'published_at'], name='app_notific_recipie_55312d_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient__isnull', True), ('scope', 'broadcast')), models.Q(('recipient__isnull', False), ('scope', 'personal')), _connector='OR'), name='finance_notification_scope_recipient_check'),
        ),
        migrations.AddIndex(
            model_name='notificationreceipt',
            index=models.Index(fields=['user', 'read_at'], name='app_notific_user_id_b4dc0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceipt',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='finance_notification_receipt_unique'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'occurred_on'], name='app_transac_owner_i_fbc86d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'type', 'status'], name='app_transac_owner_i_b761b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'occurred_on'], name='app_transac_account_60af18_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'occurred_on'], name='app_transac_categor_f494d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('account', models.F('destination_account')), _negated=True), name='finance_transaction_distinct_accounts_check'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('owner', 'idempotency_key'), name='finance_transaction_owner_idempotency_unique'),
        ),
    ]
